name: Spelling Errors Check

on: 
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:

jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - uses: codespell-project/actions-codespell@master
      with:
        ignore_words_list: carpentries,Agre 
